#!/usr/bin/env python

import re, sys

STATUS_RE = re.compile(
    '\s+\[junit\] Tests run: [\d]+, Failures: ([\d]+), Errors: ([\d]+)')
RED = "\033[1;31m%s\033[0m"
GREEN = "\033[1;32m%s\033[0m"

if __name__ == '__main__':
    line = sys.stdin.readline()
    while(line):
        match = STATUS_RE.match(line)
        if match:
            (failures, errors) = match.groups()
            if (int(failures)) > 0 or (int(errors) > 0):
                sys.stdout.write(RED % line)
            else:
                sys.stdout.write(GREEN % line)
        else:
            sys.stdout.write(line)
            
        line = sys.stdin.readline()